import React, { PureComponent } from "react";
import Context from "../../Context";
import { withRouter } from "react-router";
import { Link } from "react-router-dom";
import "./HaikuList.css";

class HaikuList extends PureComponent {
  constructor(props) {
    super(props);
    this.myRef = React.createRef();
  }

  static contextType = Context;

  componentDidMount() {
    this.context.randomIds.length > 0 && window.scrollTo(0, this.myRef.current);
  }

  onClickHaikuShift = () => {
    this.context.randomizeHaiku(this.props.history);
    window.scrollTo(0, this.myRef.current);
  };

  componentWillUnmount() {
    this.context.eraseIds();
  }

  render() {
    return (
      <div className="hlist_main">
        <nav>
          <Link className="navA" to="/">
            Haiku Dada
          </Link>
        </nav>
        {this.context.randomIds.length > 0 && (
          <div>
            <div ref={this.myRef} className="haikubox">
              <h1>Haiku Shift</h1>
              <p className="med margin">
                A study in haiku dada:
                <br />
                random phrases from the existing haiku collection.
              </p>
              <div className="haikubox3">
                <p>{this.context.haiku[0]}</p>
                <p>{this.context.haiku[1]}</p>
                <p>{this.context.haiku[2]}</p>
              </div>
              <p className="shiftp">
                Lines originally found in haikus #{this.context.randomIds[0]}, #
                {this.context.randomIds[1]}, and #{this.context.randomIds[2]}
              </p>
            </div>
            <hr className="line" />
            <button onClick={this.onClickHaikuShift}>Haiku Shift</button>
            <button onClick={(e) => this.props.history.push("/form")}>
              Haiku Generator
            </button>
            <hr className="line" />
          </div>
        )}
        <div>
          <h1 className="list_header">Haiku Collection</h1>
          <div className="cont_haikulist">
            {this.context.haikuStore.map((h, i) => (
              <div key={i} className="haikulist_box">
                <p>Haiku # {h.id}</p>
                <p>{h.date_created}</p>
                <div className="haikulist_h">
                  <p>{h.haiku[0]}</p>
                  <p>{h.haiku[1]}</p>
                  <p>{h.haiku[2]}</p>
                </div>
                {h.penname.length > 0 ? (
                  <p>Generated By: {h.penname}</p>
                ) : (
                  <p>anonymous</p>
                )}
              </div>
            ))}
          </div>
          {this.context.haikuStore.length > 0 &&
            this.context.randomIds.length === 0 && (
              <div>
                {" "}
                <p className="shiftp">
                  Haiku Shift combines random phrases from the existing haiku
                  collection.
                </p>
                <button onClick={this.onClickHaikuShift}>Haiku Shift</button>
              </div>
            )}
          {this.context.randomIds.length === 0 && (
            <button onClick={(e) => this.props.history.push("/form")}>
              Haiku Generator
            </button>
          )}
        </div>
      </div>
    );
  }
}

export default withRouter(HaikuList);
