import formHelpers from "../form-helpers";

export default [
  { word: "beach" },
  { word: "bog" },
  { word: "cave" },
  { word: "cavern" },
  { word: "cay" },
  { word: "coast" },
  { word: "copse" },
  { word: "creek" },
  { word: "dell" },
  { word: "desert" },
  { word: "fen" },
  { word: "forest" },
  { word: "glacier" },
  { word: "glen" },
  { word: "highland" },
  { word: "iceberg" },
  { word: "island" },
  { word: "jungle" },
  { word: "marsh" },
  { word: "meadow" },
  { word: "moor" },
  { word: "mountain" },
  { word: "ocean" },
  { word: "prairie" },
  { word: "reef" },
  { word: "river" },
  { word: "sandbar" },
  { word: "sea" },
  { word: "shore" },
  { word: "stream" },
  { word: "swamp" },
  { word: "tree" },
  { word: "tundra" },
  { word: "vale" },
  { word: "valley" },
  { word: "volcano" },
  { word: "wood" },
].map((obj) => {
  const syllables = formHelpers.newCount(obj.word);
  return { word: obj.word, syllables: syllables };
});
